-- Supabase Storage Security Policies for Adventure Log
-- This file implements Row Level Security (RLS) for the photos bucket
-- Ensures only the server can access storage directly

-- Enable RLS on the storage.objects table (if not already enabled)
ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist (for redeployment)
DROP POLICY IF EXISTS "Deny all direct access" ON storage.objects;
DROP POLICY IF EXISTS "Allow service role access" ON storage.objects;
DROP POLICY IF EXISTS "Allow authenticated reads via API" ON storage.objects;

-- =============================================================================
-- BUCKET: adventure-photos
-- =============================================================================

-- Policy 1: Deny all public access by default
-- This is the most restrictive policy and applies to all users
CREATE POLICY "Deny all direct access"
ON storage.objects
FOR ALL
TO public
USING (false)
WITH CHECK (false);

-- Policy 2: Allow service role full access
-- Only the server-side service role can manage files directly
CREATE POLICY "Allow service role access"
ON storage.objects
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

-- Policy 3: Allow authenticated reads via signed URLs
-- This policy allows reading via signed URLs for authenticated users
-- The application handles authorization in the API layer
CREATE POLICY "Allow authenticated reads via API"
ON storage.objects
FOR SELECT
TO authenticated
USING (
  bucket_id = 'adventure-photos' AND
  -- Only allow access to signed URLs (handled by server)
  -- The server validates permissions before generating signed URLs
  auth.role() = 'authenticated'
);

-- =============================================================================
-- BUCKET CONFIGURATION
-- =============================================================================

-- Ensure the adventure-photos bucket exists with correct settings
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'adventure-photos',
  'adventure-photos', 
  false, -- Not public - requires signed URLs
  10485760, -- 10MB limit
  ARRAY[
    'image/jpeg',
    'image/jpg', 
    'image/png',
    'image/webp'
  ]::text[]
)
ON CONFLICT (id) DO UPDATE SET
  public = false,
  file_size_limit = 10485760,
  allowed_mime_types = ARRAY[
    'image/jpeg',
    'image/jpg',
    'image/png', 
    'image/webp'
  ]::text[];

-- =============================================================================
-- SECURITY VERIFICATION QUERIES
-- =============================================================================

-- Query to verify bucket configuration
-- Run: SELECT * FROM storage.buckets WHERE id = 'adventure-photos';

-- Query to verify RLS policies are active
-- Run: SELECT * FROM pg_policies WHERE tablename = 'objects' AND schemaname = 'storage';

-- Query to test unauthorized access (should return no rows)
-- Run as anon: SELECT * FROM storage.objects WHERE bucket_id = 'adventure-photos';

-- =============================================================================
-- IMPORTANT SECURITY NOTES
-- =============================================================================

/*
1. NEVER make the bucket public - this would expose all photos directly
2. Always use signed URLs generated by the server for photo access
3. The server validates user permissions before generating signed URLs
4. Direct client access to storage is completely blocked
5. Only the service role (server) can upload/delete files
6. Users access photos through the Next.js API which handles authorization
7. Signed URLs expire after a configured time (1-4 hours typically)

FLOW:
1. User uploads -> Next.js API validates permissions -> Server uploads to Supabase
2. User views photo -> Next.js API validates permissions -> Server generates signed URL
3. Browser displays photo using temporary signed URL
4. Signed URL expires, forcing re-validation for continued access

This ensures:
- No direct access to storage
- All permissions handled by application logic
- Automatic expiration of access tokens
- Complete audit trail in application logs
*/

-- =============================================================================
-- MONITORING QUERIES (Optional - for debugging)
-- =============================================================================

-- Monitor storage usage by user folder
/*
SELECT 
  split_part(name, '/', 2) as user_id,
  COUNT(*) as photo_count,
  SUM((metadata->>'size')::bigint) as total_size_bytes,
  pg_size_pretty(SUM((metadata->>'size')::bigint)) as total_size_formatted
FROM storage.objects 
WHERE bucket_id = 'adventure-photos' 
  AND split_part(name, '/', 1) = 'photos'
GROUP BY split_part(name, '/', 2)
ORDER BY total_size_bytes DESC;
*/

-- Monitor recent uploads
/*
SELECT 
  name,
  created_at,
  (metadata->>'size')::bigint as size_bytes,
  metadata->>'mimetype' as mime_type
FROM storage.objects 
WHERE bucket_id = 'adventure-photos'
  AND created_at > NOW() - INTERVAL '24 hours'
ORDER BY created_at DESC;
*/