import type { Metadata } from "next";
import { Inter, Fraunces, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { ConditionalAuthProvider } from "@/components/auth/ConditionalAuthProvider";
import { ThemeProvider } from "@/lib/contexts/ThemeContext";
import { QueryProvider } from "@/components/providers/QueryProvider";
import { ErrorBoundary } from "@/components/ErrorBoundary";
import { ServiceWorkerRegistration } from "@/components/ServiceWorkerRegistration";
import { validateEnv } from "@/lib/utils/env";
import { AnalyticsConsent } from "@/components/legal/AnalyticsConsent";
import { ThemedToaster } from "@/components/ui/ThemedToaster";
import { GlobalMotionConfig } from "@/components/providers/GlobalMotionConfig";
import { NativeNavigationAdapter } from "@/components/capacitor/NativeNavigationAdapter";
import { NativeAppShell } from "@/components/capacitor/NativeAppShell";
import { ReferralHandler } from "@/components/referral/ReferralHandler";
import { brand } from "@/lib/brand";

// Validate environment variables at build/startup time
if (typeof window === 'undefined') {
  // Fail the build immediately when required public configuration is missing.
  // Comprehensive checks run once when the server process starts.
  validateEnv();
}

const dmSans = Inter({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  // 800 was loaded but unused anywhere in src — don't ship dead font weight.
  weight: ["400", "500", "600", "700"],
});

const playfair = Fraunces({
  variable: "--font-playfair",
  subsets: ["latin"],
  axes: ["opsz"],
});

const geistMono = JetBrains_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: {
    default: `${brand.name} — ${brand.tagline}`,
    template: `%s | ${brand.name}`
  },
  description: brand.description,
  keywords: [
    "travel",
    "adventure",
    "journeys",
    "travel blog",
    "social travel",
    "travel stories",
    "photo sharing",
    "destinations",
    "explore",
    "wanderlust",
    "travel community",
    "travel planning"
  ],
  authors: [{ name: "Adventure Log" }],
  creator: "Adventure Log",
  publisher: "Adventure Log",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL(process.env.NEXT_PUBLIC_APP_URL || 'https://adventure-log-azure.vercel.app'),
  alternates: {
    canonical: '/',
  },
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: '/',
    title: `${brand.name} — ${brand.tagline}`,
    description: 'Capture your travels, relive them on a living globe, and discover meaningful places through people you trust.',
    siteName: 'Adventure Log',
    // OG image auto-generated by src/app/opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title: `${brand.name} — ${brand.tagline}`,
    description: 'Your memories, routes, and trusted travel discoveries on one living globe.',
    images: ['/twitter-image.png'],
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  verification: {
    google: process.env.GOOGLE_SITE_VERIFICATION,
    yandex: process.env.YANDEX_VERIFICATION,
    yahoo: process.env.YAHOO_SITE_VERIFICATION,
  },
  category: 'travel',
  classification: 'Travel Social Platform',
  referrer: 'origin-when-cross-origin',
  manifest: '/manifest.json',
  icons: {
    icon: [
      { url: '/icon.svg', type: 'image/svg+xml' },
      { url: '/favicon.ico', sizes: 'any' },
      { url: '/icons/icon-192x192.png', type: 'image/png', sizes: '192x192' },
    ],
    shortcut: '/favicon.ico',
    apple: '/apple-touch-icon.png',
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: 'default',
    title: 'Adventure Log',
    startupImage: [
      {
        url: '/apple-touch-startup-image-768x1004.png',
        media: '(device-width: 768px) and (device-height: 1024px)',
      },
      {
        url: '/apple-touch-startup-image-1536x2008.png',
        media: '(device-width: 1536px) and (device-height: 2048px)',
      }
    ],
  },
  applicationName: 'Adventure Log',
  generator: 'Next.js',
  other: {
    'mobile-web-app-capable': 'yes',
    'apple-mobile-web-app-capable': 'yes',
    'application-name': 'Adventure Log',
    'msapplication-TileColor': '#1F6B57',
    'msapplication-config': '/browserconfig.xml',
  },
};

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  // Pinch zoom stays enabled (WCAG 1.4.4; this is a photo app — users must be
  // able to zoom photos). Accidental double-tap zoom on controls is prevented
  // by `touch-action: manipulation` on interactive elements instead of a
  // blanket zoom lockout. The 3D globe's in-canvas zoom (OrbitControls) calls
  // preventDefault on its gestures, so it is unaffected.
  maximumScale: 5,
  userScalable: true,
  viewportFit: 'cover',
  // Light-only app: pin the color scheme so form controls / browser chrome
  // don't render in dark on a dark-mode device.
  colorScheme: 'light',
  themeColor: '#F8F7F3'
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                // Adventure Log is light-only. Force light before first paint so
                // no stored/system preference can dark-flash the app.
                try {
                  var root = document.documentElement;
                  root.classList.remove('dark');
                  root.classList.add('light');
                  root.setAttribute('data-theme', 'light');
                  localStorage.setItem('adventure-log-theme', 'light');
                } catch(e) {}
              })();
            `,
          }}
        />
      </head>
      <body
        className={`${dmSans.variable} ${playfair.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:fixed focus:top-3 focus:left-3 focus:z-[100] focus:bg-olive-700 focus:text-white focus:rounded-md focus:px-3 focus:py-2 focus:shadow-lg"
        >
          Skip to main content
        </a>
          <ErrorBoundary>
            <QueryProvider>
              <ThemeProvider>
                <GlobalMotionConfig>
                  <ConditionalAuthProvider>
                    <ServiceWorkerRegistration />
                    <NativeNavigationAdapter />
                    <NativeAppShell />
                    <ReferralHandler />
                    <main id="main-content">{children}</main>
                    <AnalyticsConsent />
                  </ConditionalAuthProvider>
                  <ThemedToaster />
                </GlobalMotionConfig>
              </ThemeProvider>
            </QueryProvider>
          </ErrorBoundary>
      </body>
    </html>
  );
}
